version: "3.7"

services:
  groxy:
    image: cubixle/groxy:local
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - $PWD/groxy.yml:/tmp/groxy.yml
    environment: 
      - GROXY_CONFIG_FILE=/tmp/groxy.yml
